### PR TITLE
Preparations for merging PR

### PR DESCRIPTION
**Pull request by rieder**
- Moves "old" mesa to mesa-r2208
- Adds MESA "chooser" interface, using "version=" keyword to select between (currently) versions 2208 and 15140.
- Remove specific MESA version from lab.py
- few small updates to patch_files.py

### CODE REVIEW

**Comment by rieder** [comment]
@ipelupessy @rjfarmer could you check that this works for you and that this is an OK solution for choosing a specific community code version?

**Comment by ipelupessy** [comment]
I think you can just move all the import ... as ..  to the top...

**Comment by rieder** [comment]
> I think you can just move all the import ... as .. to the top...

Sure, but that would unnecessarily import other versions. Then again, maybe that's not so bad.

**Comment by rjfarmer** [comment]
So the default_path_to_MESA_data needs updating in the old mesa after its move:

````fortran
def default_path_to_MESA_data(self):
    return os.path.join(self.amuse_root_directory, 'src', 'amuse', 'community', 'mesa_r2208', 'src', 'mesa', 'data')
````    
Selecting the 15140 version works fine for me, but trying the old 2208 throws the helpful something went wrong error when trying to run a model. So i need to do some debugging to see if the selector broke things or i just have a bad install of 2208.

**Comment by rieder** [comment]
> So the default_path_to_MESA_data needs updating in the old mesa after its move:
> 
> ```fortran
> def default_path_to_MESA_data(self):
>     return os.path.join(self.amuse_root_directory, 'src', 'amuse', 'community', 'mesa_r2208', 'src', 'mesa', 'data')
> ```
> 
> Selecting the 15140 version works fine for me, but trying the old 2208 throws the helpful something went wrong error when trying to run a model. So i need to do some debugging to see if the selector broke things or i just have a bad install of 2208.

I get the same problem with v2208. Not sure why...

**Comment by rjfarmer** [comment]
There's another folder that needs moving:
````
mv $AMUSE_DIR/data/mesa $AMUSE_DIR/data/mesa_r2208 
````
(it has the input file mesa looks for when it starts). In the new mesa its not an error if this file doesn't exist, but in the old mesa it is.

**Pull request merged**
